### ISSUE TITLE
打包不了

### ISSUE THREAD

**Issue by mu-shan-beep** [lemonacy/electron-vue-element-admin#13]
C:\Users\28408\Desktop\electron-project\electron-vue-element-admin>npm  run  dev

> electron-vue-element-admin@4.2.1 dev
> node .electron-vue/dev-runner.js

         ___                      __
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___              __  __  __  __     __
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ /\ \/\ \/\ \/\ \  / ,.`\
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\\ \ \/ |\ \ \_\ \/\  __/
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/ \ \___/ \ \____/\ \____\
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/           \/__/   \/___/  \/____/
                                     \/__/
  getting ready...

┏ Main Process ---------------

  compiling...

┗ ----------------------------

i ｢wds｣: Project is running at http://localhost:9080/
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from C:\Users\28408\Desktop\electron-project\electron-vue-element-admin\

C:\Users\28408\Desktop\electron-project\electron-vue-element-admin>

C:\Users\28408\Desktop\electron-project\electron-vue-element-admin>

C:\Users\28408\Desktop\electron-project\electron-vue-element-admin>npm  run  build

> electron-vue-element-admin@4.2.1 build
> node .electron-vue/build.js && electron-builder

 ___              __                        __                       ___       __
/\_ \       __   /\ \__     ____           /\ \       __  __   __   /\_ \     /\ \
\//\ \    / ,.`\ \ \ ,_\   / ,__\  _______ \ \ \____ /\ \/\ \ /\_\  \//\ \    \_\ \
  \_\ \_ /\  __/  \ \ \/  /\__, `\/\______\ \ \  ,. \\ \ \_\ \\/\ \   \_\ \_ /\ ,. \
  /\____\\ \____\  \ \ \_ \/\____/\/______/  \ \____/ \ \____/ \ \ \  /\____\\ \____\
  \/____/ \/____/   \ \__\ \/___/             \/___/   \/___/   \/_/  \/____/ \/___ /
                     \/__/

  √ building main process
  √ building renderer process

Hash: 68799639de94c217ebea
Version: webpack 4.46.0
Time: 2217ms
Built at: 2021/04/07 上午10:48:49
  Asset      Size  Chunks             Chunk Names
main.js  1.45 KiB       0  [emitted]  main
Entrypoint main = main.js
[0] external "electron" 42 bytes {0} [built]
[1] ./src/main/index.js 1.57 KiB {0} [built]
[2] external "path" 42 bytes {0} [built]

Hash: 2908c88c7a50ab452837
Version: webpack 4.46.0
Time: 94742ms
Built at: 2021/04/07 上午10:50:22
                          Asset       Size  Chunks             Chunk Names
                           0.js   2.72 KiB       0  [emitted]
                           1.js   33.6 KiB       1  [emitted]
                          10.js     15 KiB      10  [emitted]
                          11.js   8.17 KiB      11  [emitted]
                          12.js   18.1 KiB      12  [emitted]
                          13.js   6.44 KiB      13  [emitted]
                          14.js   5.07 KiB      14  [emitted]
                          15.js   48.8 KiB      15  [emitted]
                          16.js   6.21 KiB      16  [emitted]
                          17.js    426 KiB      17  [emitted]
                          18.js   3.26 KiB      18  [emitted]
                          19.js   8.39 KiB      19  [emitted]
                           2.js     11 KiB       2  [emitted]
                          20.js   3.44 KiB      20  [emitted]
                          21.js   20.7 KiB      21  [emitted]
                          22.js   6.16 KiB      22  [emitted]
                          23.js   6.02 KiB      23  [emitted]
                          24.js   4.57 KiB      24  [emitted]
                          25.js   4.61 KiB      25  [emitted]
                          26.js   3.43 KiB      26  [emitted]
                          27.js   4.47 KiB      27  [emitted]
                          28.js   4.27 KiB      28  [emitted]
                          29.js   6.34 KiB      29  [emitted]
                           3.js   2.89 KiB       3  [emitted]
                          30.js   5.51 KiB      30  [emitted]
                          31.js   6.23 KiB      31  [emitted]
                          32.js   3.97 KiB      32  [emitted]
                          33.js   8.97 KiB      33  [emitted]
                          34.js   2.33 KiB      34  [emitted]
                          35.js   3.75 KiB      35  [emitted]
                          36.js   7.03 KiB      36  [emitted]
                          37.js   5.43 KiB      37  [emitted]
                          38.js   1.97 KiB      38  [emitted]
                          39.js   1.88 KiB      39  [emitted]
                          40.js   6.12 KiB      40  [emitted]
                          41.js   3.19 KiB      41  [emitted]
                          42.js   3.83 KiB      42  [emitted]
                          43.js   3.38 KiB      43  [emitted]
                          44.js   3.06 KiB      44  [emitted]
                          45.js   1.21 KiB      45  [emitted]
                          46.js  492 bytes      46  [emitted]
                          47.js   10.6 KiB      47  [emitted]
                          48.js   2.93 KiB      48  [emitted]
                          49.js  338 bytes      49  [emitted]
                           5.js   43.1 KiB       5  [emitted]
                          50.js  333 bytes      50  [emitted]
                          51.js  381 bytes      51  [emitted]
                          52.js  354 bytes      52  [emitted]
                          53.js  371 bytes      53  [emitted]
                          54.js  371 bytes      54  [emitted]
                          55.js  321 bytes      55  [emitted]
                          56.js  321 bytes      56  [emitted]
                          57.js  319 bytes      57  [emitted]
                          58.js  333 bytes      58  [emitted]
                          59.js  583 bytes      59  [emitted]
                           6.js   25.1 KiB       6  [emitted]
                          60.js  324 bytes      60  [emitted]
                          61.js   3.12 KiB      61  [emitted]
                           7.js    219 KiB       7  [emitted]
                           8.js   41.6 KiB       8  [emitted]
                           9.js   10.9 KiB       9  [emitted]
 fonts/element-icons--fonts.ttf   10.8 KiB          [emitted]
fonts/element-icons--fonts.woff   27.5 KiB          [emitted]
       imgs/401--401_images.gif    160 KiB          [emitted]
       imgs/404--404_images.png   95.8 KiB          [emitted]
      imgs/tui-editor--dist.png   10.6 KiB          [emitted]
   imgs/tui-editor-2x--dist.png   23.9 KiB          [emitted]
                     index.html  310 bytes          [emitted]
                    renderer.js    1.5 MiB       4  [emitted]  renderer
Entrypoint renderer = renderer.js
  [2] ./node_modules/vue-loader/lib/runtime/componentNormalizer.js 2.63 KiB {4} [built]
  [3] ./node_modules/vue/dist/vue.esm.js 319 KiB {4} [built]
  [4] ./node_modules/@babel/runtime/helpers/toConsumableArray.js 521 bytes {4} [built]
  [6] ./node_modules/vue-style-loader/lib/addStylesClient.js + 1 modules 6.71 KiB {4} [built]
      | ./node_modules/vue-style-loader/lib/addStylesClient.js 6.09 KiB [built]
      | ./node_modules/vue-style-loader/lib/listToStyles.js 637 bytes [built]
  [7] ./src/renderer/store/index.js + 1 modules 1.64 KiB {4} [built]
      | ./src/renderer/store/index.js 713 bytes [built]
      | ./src/renderer/store/getters.js 958 bytes [built]
 [10] ./src/renderer/router/index.js + 100 modules 96.7 KiB {4} [built]
      | ./src/renderer/router/index.js 10.1 KiB [built]
      | ./src/renderer/layout/index.vue 564 bytes [built]
      | ./src/renderer/router/modules/components.js 3.12 KiB [built]
      | ./src/renderer/router/modules/charts.js 944 bytes [built]
      | ./src/renderer/router/modules/table.js 1.11 KiB [built]
      | ./src/renderer/router/modules/nested.js 1.9 KiB [built]
      | ./src/renderer/layout/index.vue?vue&type=template&id=489e4daa&scoped=true& 221 bytes [built]
      | ./src/renderer/layout/index.vue?vue&type=script&lang=js& 360 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/layout/index.vue?vue&type=template&id=489e4daa&scoped=true& 725 bytes [built]
      | ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/layout/index.vue?vue&type=script&lang=js& 2.31 KiB [built]
      | ./src/renderer/components/RightPanel/index.vue 633 bytes [built]
      | ./src/renderer/layout/components/index.js 261 bytes [built]
      | ./src/renderer/layout/mixin/ResizeHandler.js 1.42 KiB [built]
      | ./src/renderer/components/RightPanel/index.vue?vue&type=template&id=40e288b9&scoped=true& 227 bytes [built]
      | ./src/renderer/components/RightPanel/index.vue?vue&type=script&lang=js& 372 bytes [built]
      |     + 86 hidden modules
 [13] external "js-cookie" 42 bytes {4} [built]
 [23] ./node_modules/element-ui/lib/element-ui.common.js 1.1 MiB {4} [built]
 [68] external "axios" 42 bytes {4} [built]
 [92] ./src/renderer/styles/element-variables.scss 521 bytes {4} [built]
[120] ./node_modules/normalize.css/normalize.css 428 bytes {4} [built]
[184] ./src/renderer/styles/index.scss 509 bytes {4} [built]
[285] external "vue-electron" 42 bytes {4} [built]
[287] ./src/renderer/main.js + 15 modules 13 KiB {4} [built]
      | ./src/renderer/main.js 1.34 KiB [built]
      | ./src/renderer/App.vue 446 bytes [built]
      | ./src/renderer/icons/index.js 324 bytes [built]
      | ./src/renderer/permission.js 4.75 KiB [built]
      | ./src/renderer/utils/error-log.js 952 bytes [built]
      | ./src/renderer/filters/index.js 1.65 KiB [built]
      | ./src/renderer/App.vue?vue&type=template&id=6ce0e9c6& 201 bytes [built]
      | ./src/renderer/App.vue?vue&type=script&lang=js& 344 bytes [built]
      | ./src/renderer/components/SvgIcon/index.vue 566 bytes [built]
      | ./src/renderer/utils/get-page-title.js 256 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=template&id=6ce0e9c6& 210 bytes [built]
      | ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=script&lang=js& 71 bytes [built]
      | ./src/renderer/components/SvgIcon/index.vue?vue&type=template&id=e23f26ac&scoped=true& 227 bytes [built]
      | ./src/renderer/components/SvgIcon/index.vue?vue&type=script&lang=js& 372 bytes [built]
      | ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/components/SvgIcon/index.vue?vue&type=template&id=e23f26ac&scoped=true& 411 bytes [built]
      |     + 1 hidden module
[288] ./src/mock/index.js + 5 modules 22.7 KiB {4} [built]
      | ./src/mock/index.js 3.41 KiB [built]
      | ./src/mock/user.js 1.45 KiB [built]
      | ./src/mock/role/index.js 1.84 KiB [built]
      | ./src/mock/article.js 4.76 KiB [built]
      | ./src/mock/remote-search.js 1.06 KiB [built]
      | ./src/mock/role/routes.js 10.2 KiB [built]
    + 564 hidden modules

WARNING in Conflict: Multiple assets emit different content to the same filename fonts/element-icons--fonts.ttf
Child HtmlWebpackCompiler:
                          Asset      Size  Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  4.91 KiB       0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 1.32 KiB {0} [built]

 OKAY  take it away `electron-builder`

  • electron-builder  version=22.4.1 os=10.0.19042
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=build\builder-effective-config.yaml
  ⨯ node_modules.Dependency.Dependencies: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|ncies" : [],
        "main|..., bigger context ...|/garycourt/JSV.git"
                }
        ],
        "dependencies" : [],
        "main" : "lib/jsv.js",
        "keywords" : ["json"|...
Error reading package.json: C:\Users\28408\Desktop\electron-project\electron-vue-element-admin\node_modules\JSV\package.json
  ⨯ C:\Users\28408\Desktop\electron-project\electron-vue-element-admin\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                                    Error: C:\Users\28408\Desktop\electron-project\electron-vue-element-admin\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                                        at ChildProcess.<anonymous> (C:\Users\28408\Desktop\electron-project\electron-vue-element-admin\node_modules\builder-util\src\util.ts:239:14)
                                                                                                                                                                                        at Object.onceWrapper (events.js:422:26)
                                                                                                                                                                                        at ChildProcess.emit (events.js:315:20)
                                                                                                                                                                                        at maybeClose (internal/child_process.js:1048:16)
                                                                                                                                                                                        at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

**Comment by xutaocc** [comment]
我也是
....
 OKAY  take it away `electron-builder`

  • electron-builder  version=22.11.7 os=10.0.19042
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=build\builder-effective-config.yaml
  ⨯ node_modules.Dependency.Dependencies: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|encies": [],
  "main|..., bigger context ...|/garycourt/JSV.git"
    }
  ],
  "dependencies": [],
  "main": "lib/jsv.js",
  "keywords": [
    "js|...
Error reading package.json: D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules\jsonlint\node_modules\JSV\package.json  
  ⨯ D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules\_app-builder-bin@3.5.13@app-builder-bin\win\x64\app-builder.exe exited with cod
e ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules\_app-buil
der-bin@3.5.13@app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules\_builder-util@22.11.7@builder-util\src\util.ts:249
:14)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-element-admin@4.2.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-vue-element-admin@4.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-07-09T15_35_22_677Z-debug.log

**Comment by Evilys** [comment]
> 我也是
> ....
> OKAY take it away `electron-builder`
> 
> • electron-builder version=22.11.7 os=10.0.19042
> • loaded configuration file=package.json ("build" field)
> • writing effective config file=build\builder-effective-config.yaml
> ⨯ node_modules.Dependency.Dependencies: ReadMapCB: expect { or n, but found [, error found in #10 byte of ...|encies": [],
> "main|..., bigger context ...|/garycourt/JSV.git"
> }
> ],
> "dependencies": [],
> "main": "lib/jsv.js",
> "keywords": [
> "js|...
> Error reading package.json: D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules\jsonlint\node_modules\JSV\package.json
> ⨯ D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules_app-builder-bin@3.5.13@app-builder-bin\win\x64\app-builder.exe exited with cod
> e ERR_ELECTRON_BUILDER_CANNOT_EXECUTE failedTask=build stackTrace=Error: D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules_app-buil
> der-bin@3.5.13@app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
> at ChildProcess. (D:\dev_lab\webstrom_space\electron-vue-element-admin\node_modules_builder-util@22.11.7@builder-util\src\util.ts:249
> :14)
> at Object.onceWrapper (events.js:482:26)
> at ChildProcess.emit (events.js:375:28)
> at maybeClose (internal/child_process.js:1055:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! electron-vue-element-admin@4.2.1 build: `node .electron-vue/build.js && electron-builder`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electron-vue-element-admin@4.2.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2021-07-09T15_35_22_677Z-debug.log

是不是node版本问题，我用v14.17.5正常打包，之前用低版本不行
